### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Strutsagget** [dawehner/replicate#3]
Hi

How do i use this module?

cant find any of the the functions in README

replicate_entity()
replicate_clone_entity()

**Comment by dawehner** [comment]
https://github.com/dawehner/replicate/blob/8.x-1.x/replicate.drush.inc#L46 has a sort of example how to use it. Sorry for the bad documentation, PRs/patches in the original project are welcomed.

**Comment by Strutsagget** [comment]
Yup found that :)
For those looking.

```
//Create Service object

 $replicator = \Drupal::service('replicate.replicator');

//Replicate entity

 $entity = $replicator->replicateEntity($originalEntity);
```
or
```
//Create Service object

$replicator = \Drupal::service('replicate.replicator');

//Replicate by passing type 'node' and nid or any other entity type and id

$entity = $replicator->replicateByEntityId($entity_type, $original_id);
```
